//pages

import 'package:flutter_playground/models/page_model.dart';
import 'package:flutter_playground/playground_pages/3d_drawer.dart';
import 'package:flutter_playground/playground_pages/api_consumer_with_cache.dart';
import 'package:flutter_playground/playground_pages/api_consumer_with_stream.dart';
import 'package:flutter_playground/playground_pages/bloc_with_get_It.dart';
import 'package:flutter_playground/playground_pages/clipper_playground.dart';
import 'package:flutter_playground/playground_pages/container_shadow.dart';
import 'package:flutter_playground/playground_pages/draggable_scrollable_sheet.dart';
import 'package:flutter_playground/playground_pages/facebook_story_ui.dart';
import 'package:flutter_playground/playground_pages/flip_page_transition.dart';
import 'package:flutter_playground/playground_pages/flutter_animation_package.dart';
import 'package:flutter_playground/playground_pages/flutter_clipper.dart';
import 'package:flutter_playground/playground_pages/flutter_inherited_widget.dart';
import 'package:flutter_playground/playground_pages/flutter_navigation_rails.dart';
import 'package:flutter_playground/playground_pages/flutter_provider.dart';
import 'package:flutter_playground/playground_pages/flutter_stateful_widget.dart';
import 'package:flutter_playground/playground_pages/get_package_state_management.dart';
import 'package:flutter_playground/playground_pages/google_map_inside_scrollview.dart';
import 'package:flutter_playground/playground_pages/google_map_polyline.dart';
import 'package:flutter_playground/playground_pages/hive_database.dart';
import 'package:flutter_playground/playground_pages/inherited_provider.dart';
import 'package:flutter_playground/playground_pages/interval_animation.dart';
import 'package:flutter_playground/playground_pages/lerp_animation.dart';
import 'package:flutter_playground/playground_pages/local_auth.dart';
import 'package:flutter_playground/playground_pages/look_rotation.dart';
import 'package:flutter_playground/playground_pages/new_localization.dart';
import 'package:flutter_playground/playground_pages/page_view_enlarge.dart';
import 'package:flutter_playground/playground_pages/proxy_provider_demo.dart';
import 'package:flutter_playground/playground_pages/real_bloc_pattern.dart';
import 'package:flutter_playground/playground_pages/scaling_page.dart';
import 'package:flutter_playground/playground_pages/shared_element_transition.dart';
import 'package:flutter_playground/playground_pages/sliver_persistent_header.dart';
import 'package:flutter_playground/playground_pages/sliver_with_tabbar.dart';
import 'package:flutter_playground/playground_pages/sqflite_todo.dart';
import 'package:flutter_playground/playground_pages/state_rebuilder_demo.dart';
import 'package:flutter_playground/playground_pages/streambuilder.dart';
import 'package:flutter_playground/playground_pages/swipe_card.dart';
import 'package:flutter_playground/playground_pages/telegram_sliver.dart';

final List<PageModel> pages = [
  PageModel(page: StreamBuilderPlayground()),
  PageModel(
      page: ScalingPage("https://picsum.photos/300"),
      shouldHaveTransition: true,
      image: "https://picsum.photos/300"),
  PageModel(page: IntervalAnimation()),
  //PageModel(page: FirebaseFaceDetectionDemo()),
  PageModel(page: SliverPersistentHeaderDemo()),
  PageModel(page: LookRotation()),
  PageModel(page: LocalAuthenthicationDemo()),
  PageModel(page: ContainerShadowDemo()),
  PageModel(page: StateRebuilderDemo()),
  PageModel(page: RealBlocPattern()),
  PageModel(page: LerpAnimationDemo()),
  PageModel(page: DraggableSrollableSheetDemo()),
  PageModel(page: GoogleMapPolyline()),
  //PageModel(page: AudioPlayerDemo()),
  PageModel(page: BlocWithGetIt()),
  PageModel(page: PageViewEnlarge()),
  PageModel(page: FlutterClipper()),
  PageModel(page: NewLocalization()),
  //PageModel(page: SoundRecorderDemo()),
  PageModel(page: FlutterProvider()),
  PageModel(page: FlutterStatefulWidget()),
  PageModel(page: TelegramSliver()),
  PageModel(page: HiveDatabase()),
  PageModel(page: ApiConsumerWithCache()),
  PageModel(page: ApiConsumerWithStream()),
  PageModel(page: FlutterInheritedWidget()),
  PageModel(page: FlutterNavigationRails()),
  PageModel(page: GetPackageStateManagement()),
  PageModel(page: FlipPageTransition()),
  PageModel(page: FlutterAnimationPackage()),
  PageModel(page: ClipperPlayground()),
  PageModel(page: ThreeDDrawer()),
  PageModel(page: SharedElementTransition()),
  PageModel(page: SwipeCard()),
  PageModel(page: ProxyProviderDemo()),
  PageModel(page: SilverAppBarWithTabBarScreen()),
  PageModel(page: GoogleMapInsideScrollView()),
  PageModel(page: FacebookStoryUI()),
  PageModel(page: SqfLiteTodoApp()),
  PageModel(page: InheritedProviderDemo()),
];
