name: flutter_playground
description: A flutter project for multi purpose playfround

version: 1.0.0+1

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  rxdart: ^0.23.1
  firebase_core: ^0.4.4
  image_picker: ^0.6.3+4
  firebase_ml_vision: ^0.9.2
  image: ^2.1.4
  local_auth: ^0.6.1+3
  flutter_colorpicker: ^0.3.2
  states_rebuilder: ^1.14.1
  google_maps_flutter: ^0.5.24+1
  location: ^2.5.3
  dio: any
  toast: ^0.1.5
  flare_flutter: ^2.0.1
  geolocator: ^5.3.0
  flutter_html: ^0.11.1
  audioplayers: ^0.14.0
  get_it: ^4.0.0
  flutter_bloc: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/pin.flr
