name: flutter_playground
description: A flutter project for multi purpose playfround

version: 1.0.0+1

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  rxdart: ^0.23.1
  #firebase_core: ^0.4.4
  image_picker: ^0.6.3+4
  #firebase_ml_vision: ^0.9.2
  image: ^2.1.4
  local_auth: ^0.6.2+1
  flutter_colorpicker: ^0.3.2
  states_rebuilder: ^1.14.1
  google_maps_flutter: ^0.5.25+1
  location: ^2.5.3
  dio: any
  toast: ^0.1.5
  flare_flutter: ^2.0.1
  provider: any
  geolocator: ^5.3.0
  flutter_html: ^0.11.1
  #audioplayers: ^0.14.0
  get_it: ^4.0.0
  flutter_bloc: ^3.2.0
  easy_localization: ^2.0.1+3
  #flutter_sound: ^3.1.10
  #audio_recorder: ^1.0.2
  font_awesome_flutter: ^8.8.1
  hive_flutter: ^0.3.0+2
  dio_http_cache: ^0.2.6
  hive: ^1.4.1+1
  get: ^2.1.1
  jin_widget_helper: ^1.3.1
  animations: ^1.0.0+5
  rect_getter: ^0.1.0
  sqflite: ^1.3.0+2

dev_dependencies:
  hive_generator: any
  build_runner: any
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - resources/language/en-US.json
    - resources/language/km-KH.json
